In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
from pathlib import Path

In [3]:
print(sys.path)

['/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/de_etl_examples/.venv/lib/python3.11/site-packages', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/de_etl_examples/src', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/de_etl_examples/.venv/lib/python3.11/site-packages/setuptools/_vendor', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/adm_integration_framework']

In [4]:
root_path = (Path(os.getcwd()).parent.parent / "src").as_posix()
root_path

'/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/adm_integration_framework/src'

In [5]:
sys.path.append(root_path)

In [42]:
import unittest
from datetime import datetime
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, Row, DecimalType
from adm.integration.adm_data_transformer import AdmDataTransformer
from adm.integration.adm_base_data_transformer import AdmBaseDataTransformer
from adm.integration.adm_table_writer import AdmTableWriter
from adm.integration.adm_table_reader import AdmTableReader
import logging

In [43]:
config_file = "use_cases/p2c_insightops/sales_order_invoice_ibmdb2.yml"
adm_table_reader = AdmTableReader(config_file)
transformer = AdmBaseDataTransformer(config_file)
transformer2 = AdmDataTransformer(config_file)
writer = AdmTableWriter(config_file)

In [44]:
df = adm_table_reader.read_source_table("ibmdb2_currencytable")
df = df.filter((F.col("FCURR") == "EUR") & (F.col("date_converted") == F.lit("2025-03-03")))
df.dtypes

INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_currencytable
INFO:adm.integration.base_integration:Applying function Name: use_cases.custom_transformations.p2c_tx.currency_convert_from_source_currency_to_target_currency_fun

[('FCURR', 'string'),
 ('TCURR', 'string'),
 ('date_converted', 'date'),
 ('exchange_rate', 'decimal(21,15)')]

In [45]:
display(df)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[FCURR: string, TCURR: string, date_converted: date, exchange_rate: decimal(21,15)]

In [48]:
df = transformer2.apply_joins("combine_1")

INFO:adm.integration.base_integration:Applying joins for combine_id: combine_1
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_inv_ord_details
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_invoice_details with alias: id
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_invoice_details
INFO:adm.integration.base_integration:Joining iod with id using condition: iod.INOR_ID = id.INVC_INOR_ID and join type: inner
INFO:adm.integration.base_integration:Schema after joining iod with id: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_profit_center with alias: pc
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_profit_center
INFO:adm.integration.base_integration:Applying function Name: use_cases.custom_transformations.p2c_tx.with_col_lit
INFO:adm.integration.base_integration:Joining iod with pc using condition: iod.INOR_COPC_ID = pc.COPC_ID and join type: inner
INFO:adm.integration.base_integration:Schema after joining iod with pc: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_term_code with alias: tc
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_term_code
INFO:adm.integration.base_integration:Joining iod with tc using condition: iod.INOR_TC_TERMS_CODE = tc.TERM_CODE and join type: inner
INFO:adm.integration.base_integration:Schema after joining iod with tc: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_vendor_customer with alias: vc
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_vendor_customer
INFO:adm.integration.base_integration:Joining iod with vc using condition: iod.INOR_SOLDTO = vc.VNCU_VENDOR_NBR and join type: left
INFO:adm.integration.base_integration:Schema after joining iod with vc: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_opencurr_currency with alias: oc
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_opencurr_currency
INFO:adm.integration.base_integration:Joining iod with oc using condition: iod.INOR_CURR_ID = oc.CURR_ID and join type: left
INFO:adm.integration.base_integration:Schema after joining iod with oc: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_open_item with alias: oi
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_open_item
INFO:adm.integration.base_integration:Joining iod with oi using condition: iod.INOR_ORIG_ORDER_NUMBER = oi.OI_ORIG_ORDER and join type: left
INFO:adm.integration.base_integration:Schema after joining iod with oi: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True), StructField('OI_ORIG_ORDER', StringType(), True), StructField('OI_TYPE', StringType(), True), StructField('OI_ITEM_FROM', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_cop_cross_reference with alias: ccr
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_cop_cross_reference
INFO:adm.integration.base_integration:Joining pc with ccr using condition: pc.COPC_CODE_int = ccr.XRFC_COMPANY and join type: left
INFO:adm.integration.base_integration:Schema after joining pc with ccr: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True), StructField('OI_ORIG_ORDER', StringType(), True), StructField('OI_TYPE', StringType(), True), StructField('OI_ITEM_FROM', StringType(), True), StructField('XRFC_COMPANY', IntegerType(), True), StructField('XRFC_COPC', IntegerType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_copc_profit_center with alias: cpc
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_copc_profit_center
INFO:adm.integration.base_integration:Joining ccr with cpc using condition: ccr.XRFC_COPC = cpc.PC_COPC and join type: left
INFO:adm.integration.base_integration:Schema after joining ccr with cpc: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True), StructField('OI_ORIG_ORDER', StringType(), True), StructField('OI_TYPE', StringType(), True), StructField('OI_ITEM_FROM', StringType(), True), StructField('XRFC_COMPANY', IntegerType(), True), StructField('XRFC_COPC', IntegerType(), True), StructField('PC_COPC', IntegerType(), True), StructField('PC_GRP_COMMODITY', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_credit_dist_list with alias: cdl
INFO:adm.integration.base_integration:Joining cpc with cdl using condition: cpc.PC_COPC = cdl.CD_COPC and join type: left
INFO:adm.integration.base_integration:Schema after joining cpc with cdl: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True), StructField('OI_ORIG_ORDER', StringType(), True), StructField('OI_TYPE', StringType(), True), StructField('OI_ITEM_FROM', StringType(), True), StructField('XRFC_COMPANY', IntegerType(), True), StructField('XRFC_COPC', IntegerType(), True), StructField('PC_COPC', IntegerType(), True), StructField('PC_GRP_COMMODITY', StringType(), True), StructField('CD_COPC', StringType(), True), StructField('CD_INTL_CREDIT_MGR', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_comd_group with alias: cg
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_comd_group
INFO:adm.integration.base_integration:Joining cpc with cg using condition: cpc.PC_GRP_COMMODITY = cg.CMDG_COMD_GRP_CD and join type: left
INFO:adm.integration.base_integration:Schema after joining cpc with cg: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True), StructField('OI_ORIG_ORDER', StringType(), True), StructField('OI_TYPE', StringType(), True), StructField('OI_ITEM_FROM', StringType(), True), StructField('XRFC_COMPANY', IntegerType(), True), StructField('XRFC_COPC', IntegerType(), True), StructField('PC_COPC', IntegerType(), True), StructField('PC_GRP_COMMODITY', StringType(), True), StructField('CD_COPC', StringType(), True), StructField('CD_INTL_CREDIT_MGR', StringType(), True), StructField('CMDG_COMD_GRP_CD', StringType(), True), StructField('CMDG_CORP_SEGMENT_CD', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_corp_segment with alias: cs
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_corp_segment
INFO:adm.integration.base_integration:Joining cg with cs using condition: cg.CMDG_CORP_SEGMENT_CD = cs.CSEG_SEGMENT_CD and join type: left
INFO:adm.integration.base_integration:Schema after joining cg with cs: StructType([StructField('INOR_ID', IntegerType(), False), StructField('INOR_COPC_ID', IntegerType(), False), StructField('INOR_TC_TERMS_CODE', StringType(), False), StructField('INOR_SOLDTO', StringType(), False), StructField('INOR_CURR_ID', IntegerType(), False), StructField('INOR_ORIG_ORDER_NUMBER', StringType(), False), StructField('INOR_SHIP_DATE', DateType(), True), StructField('INOR_ORDER_DATE', DateType(), False), StructField('INOR_TOT_EXTENDED_AMT', DecimalType(13,2), False), StructField('INVC_INOR_ID', IntegerType(), False), StructField('INVC_INVOICE_NBR', StringType(), False), StructField('INVC_INVOICE_DATE', DateType(), False), StructField('COPC_ID', IntegerType(), False), StructField('COPC_CODE', StringType(), False), StructField('COPC_CODE_int', IntegerType(), True), StructField('COPC_NAME', StringType(), False), StructField('TERM_CODE', StringType(), False), StructField('TERM_DESC', StringType(), False), StructField('VNCU_VENDOR_NBR', StringType(), True), StructField('VNCU_NAME', StringType(), True), StructField('VNCU_UPDATE_USERID', StringType(), True), StructField('CURR_ID', IntegerType(), True), StructField('CURR_CODE', StringType(), True), StructField('OI_ORIG_ORDER', StringType(), True), StructField('OI_TYPE', StringType(), True), StructField('OI_ITEM_FROM', StringType(), True), StructField('XRFC_COMPANY', IntegerType(), True), StructField('XRFC_COPC', IntegerType(), True), StructField('PC_COPC', IntegerType(), True), StructField('PC_GRP_COMMODITY', StringType(), True), StructField('CD_COPC', StringType(), True), StructField('CD_INTL_CREDIT_MGR', StringType(), True), StructField('CMDG_COMD_GRP_CD', StringType(), True), StructField('CMDG_CORP_SEGMENT_CD', StringType(), True), StructField('CSEG_SEGMENT_CD', StringType(), True), StructField('CSEG_DESC', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: ibmdb2_bs_emea_billing_entities with alias: bebe
INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_bs_emea_billing_entities
INFO:adm.integration.base_integration:Joining pc with bebe using condition: pc.COPC_CODE_int = bebe.LOCATION_CODE and join type: left

In [49]:
#display(df.filter("CURR_CODE == 'USD'"))
display(df.filter(F.col("exchange_rate").isNotNull()))

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[INOR_ID: int, INOR_COPC_ID: int, INOR_TC_TERMS_CODE: string, INOR_SOLDTO: string, INOR_CURR_ID: int, INOR_ORIG_ORDER_NUMBER: string, INOR_SHIP_DATE: date, INOR_ORDER_DATE: date, INOR_TOT_EXTENDED_AMT: decimal(13,2), INVC_INOR_ID: int, INVC_INVOICE_NBR: string, INVC_INVOICE_DATE: date, COPC_ID: int, COPC_CODE: string, COPC_CODE_int: int, COPC_NAME: string, TERM_CODE: string, TERM_DESC: string, VNCU_VENDOR_NBR: string, VNCU_NAME: string, VNCU_UPDATE_USERID: string, CURR_ID: int, CURR_CODE: string, OI_ORIG_ORDER: string, OI_TYPE: string, OI_ITEM_FROM: string, XRFC_COMPANY: int, XRFC_COPC: int, CD_COPC: string, CD_INTL_CREDIT_MGR: string, CMDG_COMD_GRP_CD: string, CMDG_CORP_SEGMENT_CD: string, PC_COPC: int, PC_GRP_COMMODITY: string, CSEG_SEGMENT_CD: string, CSEG_DESC: string, LOCATION_CODE: string, COUNTRY: string, date_converted: date, FCURR: string, TCURR: string, exchange_rate: decimal(21,15)]

In [50]:
df2 = transformer.apply_transformations("ibmdb2_joined", df)

INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_joined

In [53]:
display(df2.filter(F.col("exchange_rate").isNotNull()))

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[shipment_date: date, order_date: date, sold_to_customer_no: int, sold_to_customer_name: string, invoice_number: string, total_invoice_amount_usd: double, invoice_date: date, payment_term_code: string, payment_term_description: string, entity_document_company_code: string, entity_document_company_name: string, invoice_due_date: date, user_id: string, source_system: string, currency_code: string, segment: string, region: string, document_type: string, gbs_group: string, exchange_rate: decimal(21,15), __inserted_on: date, __inserted_timestamp: timestamp]

In [52]:
df2 = transformer.apply_transformations("ibmdb2_joined", df)
display(df2)

INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_joined

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[shipment_date: date, order_date: date, sold_to_customer_no: int, sold_to_customer_name: string, invoice_number: string, total_invoice_amount_usd: double, invoice_date: date, payment_term_code: string, payment_term_description: string, entity_document_company_code: string, entity_document_company_name: string, invoice_due_date: date, user_id: string, source_system: string, currency_code: string, segment: string, region: string, document_type: string, gbs_group: string, exchange_rate: decimal(21,15), __inserted_on: date, __inserted_timestamp: timestamp]

In [8]:
df = adm_table_reader.read_source_table("ibmdb2_inv_ord_details")
df.dtypes

INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_inv_ord_details

[('INOR_ID', 'int'),
 ('INOR_COPC_ID', 'int'),
 ('INOR_TC_TERMS_CODE', 'string'),
 ('INOR_SOLDTO', 'string'),
 ('INOR_CURR_ID', 'int'),
 ('INOR_ORIG_ORDER_NUMBER', 'string'),
 ('INOR_SHIP_DATE', 'date'),
 ('INOR_ORDER_DATE', 'date'),
 ('INOR_TOT_EXTENDED_AMT', 'decimal(13,2)')]

In [80]:
df = adm_table_reader.read_source_table("ibmdb2_profit_center")
df.columns

['COPC_ID',
 'COPC_CODE',
 'COPC_NAME',
 'COPC_DELETED',
 'COPC_CONTGRP_ID',
 'COPC_PRODUCTGROUP_ID',
 'COPC_REP_GROUP_ID',
 'COPC_COMM_REPG_ID',
 'COPC_COMP_ID']

In [9]:
df = adm_table_reader.read_source_table("ibmdb2_invoice_details")
df.dtypes

INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_invoice_details

[('INVC_INOR_ID', 'int'),
 ('INVC_INVOICE_NBR', 'string'),
 ('INVC_INVOICE_DATE', 'date')]

In [30]:
df = adm_table_reader.read_source_table("ibmdb2_term_code")
df.columns

['TERM_ID',
 'TERM_CODE',
 'TERM_DESC',
 'TERM_ABBR_DESC',
 'TERM_SALE_ID',
 'TERM_ACTIVE_SW']

In [31]:
df = adm_table_reader.read_source_table("ibmdb2_vendor_customer")
df.columns

['VNCU_ID',
 'VNCU_VENDOR_NBR',
 'VNCU_NAME',
 'VNCU_PRIMARY_PHONE',
 'VNCU_ORIG_DT',
 'VNCU_LAST_ACTIVITY_DT',
 'VNCU_UPDATE_USERID',
 'VNCU_STAT_ID',
 'VNCU_CURR_ID',
 'VNCU_REFER_VENDOR_NBR',
 'VNCU_SINGLE_REMIT_IND',
 'VNCU_SORT_NAME',
 'VNCU_TAX_ID',
 'VNCU_PRIORITY_REMARKS',
 'VNCU_NOTIFY_COUNT',
 'VNCU_INDUSTRY_CODE',
 'VNCU_VAT_TAX_ID']

In [32]:
df = adm_table_reader.read_source_table("ibmdb2_open_item")
df.columns

['OI_SEQ_NBR',
 'OI_COPC',
 'OI_ACCT_NBR',
 'OI_ITEM_DATE',
 'OI_ITEM_NBR',
 'OI_CD_DUE_DATE',
 'OI_INV_AMT',
 'OI_CURR',
 'OI_TYPE',
 'OI_NET_DUE_DATE',
 'OI_US_AMT',
 'OI_CD_INV_AMT',
 'OI_TERMS',
 'OI_REF_NBR',
 'OI_ADDED_CODE',
 'OI_DPD',
 'OI_SHIPTO',
 'OI_ORIG_ORDER',
 'OI_ORIG_INVOICE',
 'OI_CUST_ORDER_1',
 'OI_CUST_ORDER_2',
 'OI_BILL_OF_LADING',
 'OI_CAR_NUMBER',
 'OI_SALESMAN',
 'OI_LOCATION',
 'OI_BATCH_NBR',
 'OI_ITEM_FROM',
 'OI_ORIG_COPC',
 'OI_TRAFFIC_DESC',
 'OI_TRAFFIC_CODE',
 'OI_ARRIVAL_DATE',
 'OI_CRA_CODE',
 'OI_CO',
 'OI_PRODUCT_CODE',
 'OI_PRODUCT_DESC',
 'OI_PRODUCT_TYPE',
 'OI_PRODUCT_GROUP',
 'OI_GETPAID_TRANS_NBR']

In [ ]:
df = adm_table_reader.read_source_table("ibmdb2_opencurr_currency")
df.dtypes

[('CURR_ID', 'int'),
 ('CURR_CODE', 'string'),
 ('CURR_DESC', 'string'),
 ('CURR_ACTIVE', 'string'),
 ('CURR_UPDATE_BY_EMPL_NO', 'string'),
 ('CURR_LAST_UPDATE', 'timestamp')]

In [82]:

df = adm_table_reader.read_source_table("ibmdb2_cop_cross_reference")
df.dtypes

[('DERIVEDKEY', 'string'),
 ('XRFC_ID', 'int'),
 ('XRFC_XTYP_ID', 'int'),
 ('XRFC_COMPANY', 'string'),
 ('XRFC_DIVISION', 'string'),
 ('XRFC_COPC', 'string'),
 ('XRFC_LOC', 'string'),
 ('PROCESSED_FILE_PATH', 'string'),
 ('PROCESSED_FILE_NAME', 'string'),
 ('INSERTED_TIMESTAMP', 'timestamp'),
 ('INSERTED_ON', 'date'),
 ('INSERTED_YEAR', 'int'),
 ('INSERTED_MONTH', 'int'),
 ('INSERTED_DAY', 'int'),
 ('INSERTED_MONTHYEAR', 'string')]

In [35]:
df = adm_table_reader.read_source_table("ibmdb2_copc_profit_center")
df.dtypes

[('PC_COPC', 'string'),
 ('PC_BASE_CURR', 'string'),
 ('PC_GRP_COMMODITY', 'string'),
 ('PC_SUB_COMMODITY', 'string'),
 ('PC_CO_NAME', 'string'),
 ('PC_PC_NAME', 'string'),
 ('PC_COPC_DELETE', 'string'),
 ('PC_COPC4', 'string')]

In [40]:
df = adm_table_reader.read_source_table("ibmdb2_credit_dist_list")
df.dtypes

[('CD_COPC', 'string'),
 ('CD_CREDIT_MGR', 'string'),
 ('CD_CR_MGR_NAME', 'string'),
 ('CD_CREDIT_REP', 'string'),
 ('CD_CR_REP_NAME', 'string'),
 ('CD_LOCATION', 'string'),
 ('CD_DORMANT', 'string'),
 ('CD_EXECUTIVE', 'string'),
 ('CD_VICE_PRESIDENT', 'string'),
 ('CD_STATE', 'string'),
 ('CD_INTL_CREDIT_MGR', 'string'),
 ('CD_INTL_CREDIT_REP', 'string'),
 ('CD_GL_CO', 'string'),
 ('CD_AR_RESP', 'string'),
 ('CD_GL_RESP', 'string'),
 ('CD_ORIG_SYSTEM', 'string'),
 ('CD_INSURE_FLAG', 'string'),
 ('CD_CSR_IDENT', 'string')]

In [41]:
df = adm_table_reader.read_source_table("ibmdb2_comd_group")
df.dtypes

[('CMDG_COMD_GRP_CD', 'string'),
 ('CMDG_DESC', 'string'),
 ('CMDG_CORP_SEGMENT_CD', 'string')]

In [42]:
df = adm_table_reader.read_source_table("ibmdb2_corp_segment")
df.dtypes

[('CSEG_SEGMENT_CD', 'string'), ('CSEG_DESC', 'string')]

In [44]:
# df = adm_table_reader.read_source_table("ibmdb2_status_code_cust")
# df.dtypes

In [50]:
df = adm_table_reader.read_source_table("ibmdb2_currencytable")
df.dtypes

[('MANDT', 'string'),
 ('KURST', 'string'),
 ('FCURR', 'string'),
 ('TCURR', 'string'),
 ('GDATU', 'string'),
 ('UKURS', 'decimal(9,5)'),
 ('FFACT', 'decimal(9,0)'),
 ('TFACT', 'decimal(9,0)')]

In [113]:
df = adm_table_reader.read_source_table("ibmdb2_bs_emea_billing_entities")
df.dtypes

INFO:adm.integration.base_integration:Starting transformations for ID: ibmdb2_bs_emea_billing_entities

[('DERIVEDKEY', 'string'),
 ('LOCATION_CODE', 'string'),
 ('ENTITY', 'string'),
 ('LOCATION_NAME_SHORT', 'string'),
 ('ENTITYBILLING', 'string'),
 ('COUNTRY', 'string'),
 ('COUNTRY_CODE', 'string'),
 ('BUSINESS_SEGMENT', 'string'),
 ('ERP_SYSTEM', 'string'),
 ('RESP_TEAM', 'string'),
 ('PROCESSED_FILE_PATH', 'string'),
 ('PROCESSED_FILE_NAME', 'string'),
 ('INSERTED_TIMESTAMP', 'timestamp'),
 ('INSERTED_ON', 'date'),
 ('INSERTED_YEAR', 'int'),
 ('INSERTED_MONTH', 'int'),
 ('INSERTED_DAY', 'int'),
 ('INSERTED_MONTHYEAR', 'string')]

In [116]:
df.count()

43

In [115]:
display(df.groupBy("LOCATION_CODE").count())

DataFrame[LOCATION_CODE: string, count: bigint]

In [55]:
# df = adm_table_reader.read_source_table("ibmdb2_sales_orders_invoice_ibmdb2_table_name")
# df.dtypes

In [93]:
df = transformer2.apply_joins("combine_1")

INFO:adm.integration.base_integration:Applying joins for combine_id: combine_1
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_order_detail
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_customer_ledger

INFO:adm.integration.base_integration:Columns in cl: ['RPDOC', 'RPDCT', 'RPKCO', 'RPSDOC', 'RPLNID', 'payment_term_code', 'currency_code', 'RPBCRC', 'RPAG', 'RPACR', 'RPDDJ']
INFO:adm.integration.base_integration:Duplicate column detected and skipped: rr.requisition_id

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `ttf`.`requisition_id` cannot be resolved. Did you mean one of the following? [`od`.`user_id`, `od`.`document_type`, `cl`.`RPACR`, `cl`.`RPAG`, `cl`.`RPBCRC`]. SQLSTATE: 42703;
'Project ['ttf.requisition_id AS requisition_id#45564, 'ttf.job_type AS job_type#45565, 'ttf.pay_grade_band AS pay_grade_band#45566, 'ttf.hiring_manager_name AS hiring_manager_name#45567, 'ttf.recruiter_name AS recruiter_name#45568, 'ttf.organizational_level_2 AS organizational_level_2#45569, 'ttf.organizational_level_3 AS organizational_level_3#45570, 'ttf.business_id AS business_id#45571, 'rr.division AS division#45572, 'rr.old_reason_for_hire AS old_reason_for_hire#45573, 'rr.ec_reason_for_hire AS ec_reason_for_hire#45574, 'rr.additional_replacement_justification AS additional_replacement_justification#45575, 'rr.college_relations_requisition AS college_relations_requisition#45576, 'rr.fte_number_of_positions AS fte_number_of_positions#45577, 'rr.remaining_positions AS remaining_positions#45578, 'rr.approved_date AS approved_date#45579, 'rr.created_date AS created_date#45580, 'rr.open_date AS open_date#45581, 'rr.number_of_days_open AS number_of_days_open#45582, 'rr.number_of_days_on_hold AS number_of_days_on_hold#45583, 'rr.more_than_60_days_open_requisition_reason AS more_than_60_days_open_requisition_reason#45584, 'rr.more_than_60_days_open_requisition_reason_comment_text AS more_than_60_days_open_requisition_reason_comment_text#45585, 'rr.closed_date AS closed_date#45586, 'rr.canceled_date AS canceled_date#45587, ... 15 more fields]
+- Join Inner, ((((invoice_number#45546 = RPDOC#44926) AND (document_type#45547 = RPDCT#44927)) AND (SDKCO#45415 = RPKCO#44928)) AND ((SDDOCO#45315 = RPSDOC#45005) AND (SDLNID#45317 = RPLNID#45004)))
   :- SubqueryAlias od
   :  +- Project [invoice_number#45546, document_type#45547, SDKCO#45415, SDDOCO#45315, SDLNID#45317, sold_to_customer_no#45548, entity_document_company_code#45549, SDVR01#45347, SDTORG#45526, SDADDJ#45339, SDTRDJ#45336, SDIVD#45340, user_id#45550]
   :     +- Project [SDDOC#45416 AS invoice_number#45546, SDDCT#45417 AS document_type#45547, SDKCO#45415, SDDOCO#45315, SDLNID#45317, SDSHAN#45333 AS sold_to_customer_no#45548, SDCO#45320 AS entity_document_company_code#45549, SDVR01#45347, SDTORG#45526, SDADDJ#45339, SDTRDJ#45336, SDIVD#45340, SDUSER#45527 AS user_id#45550]
   :        +- Project [SDDOC#45416, SDDCT#45417, SDKCO#45415, SDDOCO#45315, SDLNID#45317, SDSHAN#45333, SDCO#45320, SDVR01#45347, SDTORG#45526, SDADDJ#45339, SDTRDJ#45336, SDIVD#45340, SDUSER#45527]
   :           +- SubqueryAlias bronze_dev01.jdexeeu_jdeproduction_proddta.f4211
   :              +- Relation bronze_dev01.jdexeeu_jdeproduction_proddta.f4211[SDKCOO#45314,SDDOCO#45315,SDDCTO#45316,SDLNID#45317,SDSFXO#45318,SDMCU#45319,SDCO#45320,SDOKCO#45321,SDOORN#45322,SDOCTO#45323,SDOGNO#45324,SDRKCO#45325,SDRORN#45326,SDRCTO#45327,SDRLLN#45328,SDDMCT#45329,SDDMCS#45330,SDBALU#45331,SDAN8#45332,SDSHAN#45333,SDPA8#45334,SDDRQJ#45335,SDTRDJ#45336,SDPDDJ#45337,... 194 more fields] parquet
   +- SubqueryAlias cl
      +- Project [RPDOC#44926, RPDCT#44927, RPKCO#44928, RPSDOC#45005, RPLNID#45004, payment_term_code#45071, currency_code#45072, RPBCRC#44956, RPAG#44949, RPACR#44961, RPDDJ#44981]
         +- Project [RPDOC#44926, RPDCT#44927, RPKCO#44928, RPSDOC#45005, RPLNID#45004, RPPTC#44980 AS payment_term_code#45071, RPCRCD#44958 AS currency_code#45072, RPBCRC#44956, RPAG#44949, RPACR#44961, RPDDJ#44981]
            +- Project [RPDOC#44926, RPDCT#44927, RPKCO#44928, RPSDOC#45005, RPLNID#45004, RPPTC#44980, RPCRCD#44958, RPBCRC#44956, RPAG#44949, RPACR#44961, RPDDJ#44981]
               +- SubqueryAlias bronze_dev01.jdexeeu_jdeproduction_proddta.f03b11
                  +- Relation bronze_dev01.jdexeeu_jdeproduction_proddta.f03b11[RPDOC#44926,RPDCT#44927,RPKCO#44928,RPSFX#44929,RPAN8#44930,RPDGJ#44931,RPDIVJ#44932,RPICUT#44933,RPICU#44934,RPDICJ#44935,RPFY#44936,RPCTRY#44937,RPPN#44938,RPCO#44939,RPGLC#44940,RPAID#44941,RPPA8#44942,RPAN8J#44943,RPPYR#44944,RPPOST#44945,RPISTR#44946,RPBALJ#44947,RPPST#44948,RPAG#44949,... 109 more fields] parquet


JVM stacktrace:
org.apache.spark.sql.catalyst.ExtendedAnalysisException
	at org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:454)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:171)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$8(CheckAnalysis.scala:356)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$8$adapted(CheckAnalysis.scala:341)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:293)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:292)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:292)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:292)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:341)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:341)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:341)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:216)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:293)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:216)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:198)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:369)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:186)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:174)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:174)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:369)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$2(Analyzer.scala:424)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:194)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:424)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:443)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:421)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:290)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:489)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:653)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$4(QueryExecution.scala:653)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1219)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:652)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:648)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1210)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:648)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:284)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:283)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:265)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:105)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1210)
	at org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1217)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1217)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:103)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.process(SparkConnectAnalyzeHandler.scala:86)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$3(SparkConnectAnalyzeHandler.scala:61)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$3$adapted(SparkConnectAnalyzeHandler.scala:60)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:392)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1210)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:392)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:84)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:240)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:83)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:391)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$1(SparkConnectAnalyzeHandler.scala:60)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$1$adapted(SparkConnectAnalyzeHandler.scala:45)
	at com.databricks.spark.connect.logging.rpc.SparkConnectRpcMetricsCollectorUtils$.collectMetrics(SparkConnectRpcMetricsCollector.scala:268)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.handle(SparkConnectAnalyzeHandler.scala:44)
	at org.apache.spark.sql.connect.service.SparkConnectService.analyzePlan(SparkConnectService.scala:104)
	at org.apache.spark.connect.proto.SparkConnectServiceGrpc$MethodHandlers.invoke(SparkConnectServiceGrpc.java:801)
	at grpc_shaded.io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at com.databricks.spark.connect.service.AuthenticationInterceptor$AuthenticatedServerCallListener.$anonfun$onHalfClose$1(AuthenticationInterceptor.scala:351)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.spark.connect.service.RequestContext.$anonfun$runWith$3(RequestContext.scala:295)
	at com.databricks.spark.connect.service.RequestContext$.com$databricks$spark$connect$service$RequestContext$$withLocalProperties(RequestContext.scala:504)
	at com.databricks.spark.connect.service.RequestContext.$anonfun$runWith$2(RequestContext.scala:295)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:48)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:276)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:272)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:46)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:43)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:30)
	at com.databricks.spark.util.UniverseAttributionContextWrapper.withValue(AttributionContextUtils.scala:228)
	at com.databricks.spark.connect.service.RequestContext.$anonfun$runWith$1(RequestContext.scala:294)
	at com.databricks.spark.connect.service.RequestContext.withContext(RequestContext.scala:307)
	at com.databricks.spark.connect.service.RequestContext.runWith(RequestContext.scala:287)
	at com.databricks.spark.connect.service.AuthenticationInterceptor$AuthenticatedServerCallListener.onHalfClose(AuthenticationInterceptor.scala:351)
	at grpc_shaded.io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at grpc_shaded.io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at grpc_shaded.io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at grpc_shaded.io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at grpc_shaded.io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
	at grpc_shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at grpc_shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

In [73]:
df = transformer.apply_transformations("ffjt", df)

INFO:adm.integration.base_integration:Starting transformations for ID: ffjt

In [ ]:
writer.write_table("silver_globlal_hr_request_poc", df)

INFO:adm.integration.base_integration:Getting schema from schema file use_cases/h2r/h2r_silver_head_count_poc_schema.json for sandbox.de_ref_silver_mikesturwoldcontractor.silver_head_count_poc

INFO:adm.integration.base_integration:Number of records written to table sandbox.de_ref_silver_mikesturwoldcontractor.silver_head_count_poc: 200

In [41]:
df = adm_table_reader.read_source_table("req_report")
#df_payroll = adm_table_reader.read_source_table("payroll")
#df_employee = adm_table_reader.read_source_table("employee")
#df_employee = transformer.apply_transformations("employee_new", df_employee)
#df_employee = transformer.apply_transformations("employee_expr", df_employee)

#df = transformer2.apply_joins("emp_payroll")
# df = transformer.apply_transformations("employee", df)
#df = transformer.apply_transformations("employee_expr_new", df_employee)
#df = df.select(tgt_cols)
#writer = AdmTableWriter("scratch/mike/h2r_silver_head_count_poc.yml")
#writer.write_table("silver_head_count_poc", df)

INFO:adm.integration.base_integration:Starting transformations for ID: req_report

In [0]:
#Source/adm_integration_framework/scratch/mike/h2r_head_count_poc.yml
#adm_table_reader = AdmTableReader("scratch/mike/h2r_silver_head_count_poc.yml")
#df_payroll = adm_table_reader.read_source_table("payroll")
#df_employee= adm_table_reader.read_source_table("employee")
#display(df_employee.select("bus_id","bus_id_trim"))
#display(result_df.selectExpr("* except(Emp_ID, First_Name)"))

In [0]:
#transformer = AdmBaseDataTransformer("scratch/mike/h2r_head_count_poc.yml")
#tx = "rn"

#result_df = transformer.apply_transformations("rn", result_df)
#result_df = transformer.apply_transformations("cast_cols", result_df)
#display(result_df)
#display(transformed_df.selectExpr("*", "cast(overtime_pay as decimal(10,2)) as overtime_pay"))
# why do i need to setup logger here?
# fixed by adding self.logger to adm_base_data_transformer

# column expressions duplicate columns if * specified

#transformer = AdmDataTransformer("scratch/mike/h2r_silver_head_count_poc.yml")
#result_df = transformer.apply_joins("emp_payroll")

In [0]:
display(result_df)

In [0]:
df = result_df.transform(p2c_custom_tranformatin, Col, cole3)

In [0]:
writer = AdmTableWriter("scratch/mike/h2r_silver_head_count_poc.yml")
# why does writer create the table?
# why does it need a schema file?
writer.write_table("silver_head_count_poc", result_df)

In [0]:
for x in spark.table("sandbox.h2r_dbx_poc.ec_employee").columns:
    print(x)

In [0]:
for x in spark.table("sandbox.h2r_dbx_poc.ec_payroll").columns:
    print(x)