In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
from pathlib import Path

In [3]:
print(sys.path)

['/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/de_etl_examples/.venv/lib/python3.11/site-packages', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/de_etl_examples/src', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/de_etl_examples/.venv/lib/python3.11/site-packages/setuptools/_vendor', '/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/adm_integration_framework']

In [4]:
root_path = (Path(os.getcwd()).parent.parent / "src").as_posix()
root_path

'/Users/mike.sturwold/CodeProjects/ADM/dna-common-all-databricks-templates/Source/adm_integration_framework/src'

In [5]:
sys.path.append(root_path)

In [14]:
import unittest
from datetime import datetime
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, Row, DecimalType
from wilsonelser.transformation.data_transformer import DataTransformer
from wilsonelser.transformation.base_data_transformer import BaseDataTransformer
from wilsonelser.transformation.table_writer import TableWriter
from wilsonelser.transformation.table_reader import TableReader
import logging

In [15]:
config_file = "use_cases/p2c_insightops/sales_order_invoice_jdexeeu.yml"
table_reader = TableReader(config_file)
transformer = BaseDataTransformer(config_file)
transformer2 = DataTransformer(config_file)
writer = TableWriter(config_file)

In [ ]:
display(df.withColumn("y", F.lit("A")))

In [21]:
df = table_reader.read_source_table("jdexeeu_order_detail")
display(df.withColumn("x", 
                      F.to_date(F.substring(F.col("SDTRDJ").cast(StringType()),2,5), 'yyDDD')
                      )
         .withColumn("y", F.substring(F.col("SDTRDJ").cast(StringType()),2,1))
                      )

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_order_detail
INFO:adm.integration.base_integration:Applying function Name: use_cases.custom_transformations.p2c_tx.convert_julian_dates

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[invoice_number: double, document_type: string, SDKCO: string, SDDOCO: double, SDLNID: double, sold_to_customer_no: double, entity_document_company_code: int, SDVR01: string, SDTORG: string, SDADDJ: date, SDTRDJ: decimal(18,0), SDIVD: decimal(18,0), user_id: string, x: date, y: string]

In [12]:
df = transformer2.apply_joins("combine_1")

INFO:adm.integration.base_integration:Applying joins for combine_id: combine_1
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_order_detail
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_customer_ledger with alias: cl
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_customer_ledger
INFO:adm.integration.base_integration:Joining od with cl using condition: od.invoice_number = cl.RPDOC  and od.document_type = cl.RPDCT  and od.SDKCO = cl.RPKCO  and od.SDDOCO = cl.RPSDOC  and od.SDLNID = cl.RPLNID and join type: inner
INFO:adm.integration.base_integration:Schema after joining od with cl: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_payment_terms with alias: pt
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_payment_terms
INFO:adm.integration.base_integration:Joining cl with pt using condition: cl.payment_term_code = pt.PNPTC and join type: left
INFO:adm.integration.base_integration:Schema after joining cl with pt: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True), StructField('payment_term_description', StringType(), True), StructField('PNPTC', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_address_book_master with alias: abm
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_address_book_master
INFO:adm.integration.base_integration:Joining od with abm using condition: od.sold_to_customer_no = abm.ABAN8 and join type: left
INFO:adm.integration.base_integration:Schema after joining od with abm: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True), StructField('payment_term_description', StringType(), True), StructField('PNPTC', StringType(), True), StructField('sold_to_customer_name', StringType(), True), StructField('ABAN8', DoubleType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_foundation_env with alias: fe
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_foundation_env
INFO:adm.integration.base_integration:Joining od with fe using condition: od.entity_document_company_code = fe.CCCO and join type: left
INFO:adm.integration.base_integration:Schema after joining od with fe: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True), StructField('payment_term_description', StringType(), True), StructField('PNPTC', StringType(), True), StructField('sold_to_customer_name', StringType(), True), StructField('ABAN8', DoubleType(), True), StructField('CCCO', IntegerType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_entity_mapping with alias: em
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_entity_mapping
INFO:adm.integration.base_integration:Joining od with em using condition: od.entity_document_company_code = COMPANY_CODE and join type: left
INFO:adm.integration.base_integration:Schema after joining od with em: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True), StructField('payment_term_description', StringType(), True), StructField('PNPTC', StringType(), True), StructField('sold_to_customer_name', StringType(), True), StructField('ABAN8', DoubleType(), True), StructField('CCCO', IntegerType(), True), StructField('COMPANY_CODE', IntegerType(), True), StructField('entity_document_company_name', StringType(), True), StructField('Region', StringType(), True), StructField('segment', StringType(), True), StructField('COUNTRY', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_credit_dist_list with alias: cdl
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_credit_dist_list
INFO:adm.integration.base_integration:Joining od with cdl using condition: od.entity_document_company_code = cdl.CD_COPC and join type: left
INFO:adm.integration.base_integration:Schema after joining od with cdl: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True), StructField('payment_term_description', StringType(), True), StructField('PNPTC', StringType(), True), StructField('sold_to_customer_name', StringType(), True), StructField('ABAN8', DoubleType(), True), StructField('CCCO', IntegerType(), True), StructField('COMPANY_CODE', IntegerType(), True), StructField('entity_document_company_name', StringType(), True), StructField('Region', StringType(), True), StructField('segment', StringType(), True), StructField('COUNTRY', StringType(), True), StructField('CD_COPC', IntegerType(), True), StructField('CD_LOCATION', StringType(), True), StructField('CD_INTL_CREDIT_REP', StringType(), True)])
INFO:adm.integration.base_integration:Reading and selecting columns for source_id: jdexeeu_gbs_emea_billing_entities with alias: gebe
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_gbs_emea_billing_entities
INFO:adm.integration.base_integration:Joining cdl with gebe using condition: cdl.CD_LOCATION = gebe.LOCATION_CODE and join type: left
INFO:adm.integration.base_integration:Schema after joining cdl with gebe: StructType([StructField('invoice_number', DoubleType(), True), StructField('document_type', StringType(), True), StructField('sold_to_customer_no', DoubleType(), True), StructField('entity_document_company_code', IntegerType(), True), StructField('user_id', StringType(), True), StructField('SDKCO', StringType(), True), StructField('SDDOCO', DoubleType(), False), StructField('SDLNID', DoubleType(), False), StructField('SDVR01', StringType(), True), StructField('SDADDJ', DecimalType(18,0), True), StructField('SDADDJ_jd', DateType(), True), StructField('RPDOC', DoubleType(), False), StructField('RPDCT', StringType(), False), StructField('RPKCO', StringType(), False), StructField('RPSDOC', DoubleType(), True), StructField('RPLNID', DoubleType(), True), StructField('RPAG', DoubleType(), True), StructField('RPACR', DoubleType(), True), StructField('RPBCRC', StringType(), True), StructField('payment_term_code', StringType(), True), StructField('currency_code', StringType(), True), StructField('payment_term_description', StringType(), True), StructField('PNPTC', StringType(), True), StructField('sold_to_customer_name', StringType(), True), StructField('ABAN8', DoubleType(), True), StructField('CCCO', IntegerType(), True), StructField('COMPANY_CODE', IntegerType(), True), StructField('entity_document_company_name', StringType(), True), StructField('Region', StringType(), True), StructField('segment', StringType(), True), StructField('COUNTRY', StringType(), True), StructField('CD_COPC', IntegerType(), True), StructField('CD_LOCATION', StringType(), True), StructField('CD_INTL_CREDIT_REP', StringType(), True), StructField('LOCATION_CODE', StringType(), True)])
INFO:adm.integration.base_integration:Done applying joins
INFO:adm.integration.base_integration:Final columns after join: ['invoice_number', 'document_type', 'sold_to_customer_no', 'entity_document_company_code', 'user_id', 'SDKCO', 'SDDOCO', 'SDLNID', 'SDVR01', 'SDADDJ', 'SDADDJ_jd', 'RPDOC', 'RPDCT', 'RPKCO', 'RPSDOC', 'RPLNID', 'RPAG', 'RPACR', 'RPBCRC', 'payment_term_code', 'currency_code', 'payment_term_description', 'PNPTC', 'sold_to_customer_name', 'ABAN8', 'CCCO', 'COMPANY_CODE', 'entity_document_company_name', 'Region', 'segment', 'COUNTRY', 'CD_COPC', 'CD_LOCATION', 'CD_INTL_CREDIT_REP', 'LOCATION_CODE']
INFO:adm.integration.base_integration:Completed joins for combine_id: combine_1

In [13]:
display(df)
df.dtypes

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[invoice_number: double, document_type: string, sold_to_customer_no: double, entity_document_company_code: int, user_id: string, SDKCO: string, SDDOCO: double, SDLNID: double, SDVR01: string, SDADDJ: decimal(18,0), SDADDJ_jd: date, RPDOC: double, RPDCT: string, RPKCO: string, RPSDOC: double, RPLNID: double, RPAG: double, RPACR: double, RPBCRC: string, payment_term_code: string, currency_code: string, payment_term_description: string, PNPTC: string, sold_to_customer_name: string, ABAN8: double, CCCO: int, COMPANY_CODE: int, entity_document_company_name: string, Region: string, segment: string, COUNTRY: string, CD_COPC: int, CD_LOCATION: string, CD_INTL_CREDIT_REP: string, LOCATION_CODE: string]

[('invoice_number', 'double'),
 ('document_type', 'string'),
 ('sold_to_customer_no', 'double'),
 ('entity_document_company_code', 'int'),
 ('user_id', 'string'),
 ('SDKCO', 'string'),
 ('SDDOCO', 'double'),
 ('SDLNID', 'double'),
 ('SDVR01', 'string'),
 ('SDADDJ', 'decimal(18,0)'),
 ('SDADDJ_jd', 'date'),
 ('RPDOC', 'double'),
 ('RPDCT', 'string'),
 ('RPKCO', 'string'),
 ('RPSDOC', 'double'),
 ('RPLNID', 'double'),
 ('RPAG', 'double'),
 ('RPACR', 'double'),
 ('RPBCRC', 'string'),
 ('payment_term_code', 'string'),
 ('currency_code', 'string'),
 ('payment_term_description', 'string'),
 ('PNPTC', 'string'),
 ('sold_to_customer_name', 'string'),
 ('ABAN8', 'double'),
 ('CCCO', 'int'),
 ('COMPANY_CODE', 'int'),
 ('entity_document_company_name', 'string'),
 ('Region', 'string'),
 ('segment', 'string'),
 ('COUNTRY', 'string'),
 ('CD_COPC', 'int'),
 ('CD_LOCATION', 'string'),
 ('CD_INTL_CREDIT_REP', 'string'),
 ('LOCATION_CODE', 'string')]

In [113]:
df2 = transformer.apply_transformations("jdexeeu_joined", df)

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_joined

In [114]:
display(df2)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[invoice_number: int, total_invoice_amount_usd: double, payment_term_code: string, entity_document_company_code: int, entity_document_company_name: string, user_id: string, payment_term_description: string, sold_to_customer_no: int, document_type: string, sold_to_customer_no: int, sold_to_customer_name: string, source_system: string, currency_code: string, region: string, document_type: string, segment: string, country: string, gbs_group: string, __inserted_on: date]

In [104]:
df = table_reader.read_source_table("jdexeeu_order_detail")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_order_detail

['invoice_number',
 'document_type',
 'SDKCO',
 'SDDOCO',
 'SDLNID',
 'sold_to_customer_no',
 'entity_document_company_code',
 'SDVR01',
 'SDTORG',
 'SDADDJ',
 'SDTRDJ',
 'SDIVD',
 'user_id']

In [76]:
df = table_reader.read_source_table("jdexeeu_customer_ledger")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_customer_ledger

['RPDOC',
 'RPDCT',
 'RPKCO',
 'RPSDOC',
 'RPLNID',
 'payment_term_code',
 'currency_code',
 'RPBCRC',
 'RPAG',
 'RPACR',
 'RPDDJ']

In [89]:
df = table_reader.read_source_table("jdexeeu_payment_terms")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_payment_terms

['PNPTC', 'payment_term_description']

In [78]:
df = table_reader.read_source_table("jdexeeu_foundation_env")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_foundation_env

['CCCO']

In [79]:
df = table_reader.read_source_table("jdexeeu_currencytable")
df.columns

['MANDT', 'KURST', 'FCURR', 'TCURR', 'GDATU', 'UKURS', 'FFACT', 'TFACT']

In [80]:
df = table_reader.read_source_table("jdexeeu_address_book_master")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_address_book_master

['ABAN8', 'sol_to_customer_name']

In [57]:
df = table_reader.read_source_table("jdexeeu_entity_mapping")
df.dtypes

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_entity_mapping

[('COMPANY_CODE', 'string'),
 ('entity_document_company_name', 'string'),
 ('Region', 'string'),
 ('segment', 'string'),
 ('COUNTRY', 'string')]

In [58]:
display(df)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[COMPANY_CODE: string, entity_document_company_name: string, Region: string, segment: string, COUNTRY: string]

In [84]:
# df = table_reader.read_source_table("jdexeeu_copc_cross_reference")
# df.columns

In [86]:
# df = table_reader.read_source_table("jdexeeu_copc_profit_center")
# df.columns

In [87]:
df = table_reader.read_source_table("jdexeeu_credit_dist_list")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_credit_dist_list

['CD_COPC', 'CD_LOCATION', 'CD_INTL_CREDIT_REP']

In [88]:
df = table_reader.read_source_table("jdexeeu_gbs_emea_billing_entities")
df.columns

INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_gbs_emea_billing_entities

['LOCATION_CODE']

In [93]:
df = transformer2.apply_joins("combine_1")

INFO:adm.integration.base_integration:Applying joins for combine_id: combine_1
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_order_detail
INFO:adm.integration.base_integration:Starting transformations for ID: jdexeeu_customer_ledger

INFO:adm.integration.base_integration:Columns in cl: ['RPDOC', 'RPDCT', 'RPKCO', 'RPSDOC', 'RPLNID', 'payment_term_code', 'currency_code', 'RPBCRC', 'RPAG', 'RPACR', 'RPDDJ']
INFO:adm.integration.base_integration:Duplicate column detected and skipped: rr.requisition_id

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `ttf`.`requisition_id` cannot be resolved. Did you mean one of the following? [`od`.`user_id`, `od`.`document_type`, `cl`.`RPACR`, `cl`.`RPAG`, `cl`.`RPBCRC`]. SQLSTATE: 42703;
'Project ['ttf.requisition_id AS requisition_id#45564, 'ttf.job_type AS job_type#45565, 'ttf.pay_grade_band AS pay_grade_band#45566, 'ttf.hiring_manager_name AS hiring_manager_name#45567, 'ttf.recruiter_name AS recruiter_name#45568, 'ttf.organizational_level_2 AS organizational_level_2#45569, 'ttf.organizational_level_3 AS organizational_level_3#45570, 'ttf.business_id AS business_id#45571, 'rr.division AS division#45572, 'rr.old_reason_for_hire AS old_reason_for_hire#45573, 'rr.ec_reason_for_hire AS ec_reason_for_hire#45574, 'rr.additional_replacement_justification AS additional_replacement_justification#45575, 'rr.college_relations_requisition AS college_relations_requisition#45576, 'rr.fte_number_of_positions AS fte_number_of_positions#45577, 'rr.remaining_positions AS remaining_positions#45578, 'rr.approved_date AS approved_date#45579, 'rr.created_date AS created_date#45580, 'rr.open_date AS open_date#45581, 'rr.number_of_days_open AS number_of_days_open#45582, 'rr.number_of_days_on_hold AS number_of_days_on_hold#45583, 'rr.more_than_60_days_open_requisition_reason AS more_than_60_days_open_requisition_reason#45584, 'rr.more_than_60_days_open_requisition_reason_comment_text AS more_than_60_days_open_requisition_reason_comment_text#45585, 'rr.closed_date AS closed_date#45586, 'rr.canceled_date AS canceled_date#45587, ... 15 more fields]
+- Join Inner, ((((invoice_number#45546 = RPDOC#44926) AND (document_type#45547 = RPDCT#44927)) AND (SDKCO#45415 = RPKCO#44928)) AND ((SDDOCO#45315 = RPSDOC#45005) AND (SDLNID#45317 = RPLNID#45004)))
   :- SubqueryAlias od
   :  +- Project [invoice_number#45546, document_type#45547, SDKCO#45415, SDDOCO#45315, SDLNID#45317, sold_to_customer_no#45548, entity_document_company_code#45549, SDVR01#45347, SDTORG#45526, SDADDJ#45339, SDTRDJ#45336, SDIVD#45340, user_id#45550]
   :     +- Project [SDDOC#45416 AS invoice_number#45546, SDDCT#45417 AS document_type#45547, SDKCO#45415, SDDOCO#45315, SDLNID#45317, SDSHAN#45333 AS sold_to_customer_no#45548, SDCO#45320 AS entity_document_company_code#45549, SDVR01#45347, SDTORG#45526, SDADDJ#45339, SDTRDJ#45336, SDIVD#45340, SDUSER#45527 AS user_id#45550]
   :        +- Project [SDDOC#45416, SDDCT#45417, SDKCO#45415, SDDOCO#45315, SDLNID#45317, SDSHAN#45333, SDCO#45320, SDVR01#45347, SDTORG#45526, SDADDJ#45339, SDTRDJ#45336, SDIVD#45340, SDUSER#45527]
   :           +- SubqueryAlias bronze_dev01.jdexeeu_jdeproduction_proddta.f4211
   :              +- Relation bronze_dev01.jdexeeu_jdeproduction_proddta.f4211[SDKCOO#45314,SDDOCO#45315,SDDCTO#45316,SDLNID#45317,SDSFXO#45318,SDMCU#45319,SDCO#45320,SDOKCO#45321,SDOORN#45322,SDOCTO#45323,SDOGNO#45324,SDRKCO#45325,SDRORN#45326,SDRCTO#45327,SDRLLN#45328,SDDMCT#45329,SDDMCS#45330,SDBALU#45331,SDAN8#45332,SDSHAN#45333,SDPA8#45334,SDDRQJ#45335,SDTRDJ#45336,SDPDDJ#45337,... 194 more fields] parquet
   +- SubqueryAlias cl
      +- Project [RPDOC#44926, RPDCT#44927, RPKCO#44928, RPSDOC#45005, RPLNID#45004, payment_term_code#45071, currency_code#45072, RPBCRC#44956, RPAG#44949, RPACR#44961, RPDDJ#44981]
         +- Project [RPDOC#44926, RPDCT#44927, RPKCO#44928, RPSDOC#45005, RPLNID#45004, RPPTC#44980 AS payment_term_code#45071, RPCRCD#44958 AS currency_code#45072, RPBCRC#44956, RPAG#44949, RPACR#44961, RPDDJ#44981]
            +- Project [RPDOC#44926, RPDCT#44927, RPKCO#44928, RPSDOC#45005, RPLNID#45004, RPPTC#44980, RPCRCD#44958, RPBCRC#44956, RPAG#44949, RPACR#44961, RPDDJ#44981]
               +- SubqueryAlias bronze_dev01.jdexeeu_jdeproduction_proddta.f03b11
                  +- Relation bronze_dev01.jdexeeu_jdeproduction_proddta.f03b11[RPDOC#44926,RPDCT#44927,RPKCO#44928,RPSFX#44929,RPAN8#44930,RPDGJ#44931,RPDIVJ#44932,RPICUT#44933,RPICU#44934,RPDICJ#44935,RPFY#44936,RPCTRY#44937,RPPN#44938,RPCO#44939,RPGLC#44940,RPAID#44941,RPPA8#44942,RPAN8J#44943,RPPYR#44944,RPPOST#44945,RPISTR#44946,RPBALJ#44947,RPPST#44948,RPAG#44949,... 109 more fields] parquet


JVM stacktrace:
org.apache.spark.sql.catalyst.ExtendedAnalysisException
	at org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:454)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:171)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$8(CheckAnalysis.scala:356)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$8$adapted(CheckAnalysis.scala:341)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:293)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:292)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:292)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:292)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:341)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:341)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:341)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:216)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:293)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:216)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:198)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:369)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:186)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:174)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:174)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:369)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$2(Analyzer.scala:424)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:194)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:424)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:443)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:421)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:290)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:489)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:653)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$4(QueryExecution.scala:653)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1219)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:652)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:648)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1210)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:648)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:284)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:283)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:265)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:105)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1210)
	at org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1217)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1217)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:103)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.process(SparkConnectAnalyzeHandler.scala:86)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$3(SparkConnectAnalyzeHandler.scala:61)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$3$adapted(SparkConnectAnalyzeHandler.scala:60)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:392)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1210)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:392)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:84)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:240)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:83)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:391)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$1(SparkConnectAnalyzeHandler.scala:60)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.$anonfun$handle$1$adapted(SparkConnectAnalyzeHandler.scala:45)
	at com.databricks.spark.connect.logging.rpc.SparkConnectRpcMetricsCollectorUtils$.collectMetrics(SparkConnectRpcMetricsCollector.scala:268)
	at org.apache.spark.sql.connect.service.SparkConnectAnalyzeHandler.handle(SparkConnectAnalyzeHandler.scala:44)
	at org.apache.spark.sql.connect.service.SparkConnectService.analyzePlan(SparkConnectService.scala:104)
	at org.apache.spark.connect.proto.SparkConnectServiceGrpc$MethodHandlers.invoke(SparkConnectServiceGrpc.java:801)
	at grpc_shaded.io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at com.databricks.spark.connect.service.AuthenticationInterceptor$AuthenticatedServerCallListener.$anonfun$onHalfClose$1(AuthenticationInterceptor.scala:351)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.spark.connect.service.RequestContext.$anonfun$runWith$3(RequestContext.scala:295)
	at com.databricks.spark.connect.service.RequestContext$.com$databricks$spark$connect$service$RequestContext$$withLocalProperties(RequestContext.scala:504)
	at com.databricks.spark.connect.service.RequestContext.$anonfun$runWith$2(RequestContext.scala:295)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:48)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:276)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:272)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:46)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:43)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:30)
	at com.databricks.spark.util.UniverseAttributionContextWrapper.withValue(AttributionContextUtils.scala:228)
	at com.databricks.spark.connect.service.RequestContext.$anonfun$runWith$1(RequestContext.scala:294)
	at com.databricks.spark.connect.service.RequestContext.withContext(RequestContext.scala:307)
	at com.databricks.spark.connect.service.RequestContext.runWith(RequestContext.scala:287)
	at com.databricks.spark.connect.service.AuthenticationInterceptor$AuthenticatedServerCallListener.onHalfClose(AuthenticationInterceptor.scala:351)
	at grpc_shaded.io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at grpc_shaded.io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at grpc_shaded.io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at grpc_shaded.io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at grpc_shaded.io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
	at grpc_shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at grpc_shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

In [73]:
df = transformer.apply_transformations("ffjt", df)

INFO:adm.integration.base_integration:Starting transformations for ID: ffjt

In [ ]:
writer.write_table("silver_globlal_hr_request_poc", df)

INFO:adm.integration.base_integration:Getting schema from schema file use_cases/h2r/h2r_silver_head_count_poc_schema.json for sandbox.de_ref_silver_mikesturwoldcontractor.silver_head_count_poc

INFO:adm.integration.base_integration:Number of records written to table sandbox.de_ref_silver_mikesturwoldcontractor.silver_head_count_poc: 200

In [41]:
df = table_reader.read_source_table("req_report")
#df_payroll = table_reader.read_source_table("payroll")
#df_employee = table_reader.read_source_table("employee")
#df_employee = transformer.apply_transformations("employee_new", df_employee)
#df_employee = transformer.apply_transformations("employee_expr", df_employee)

#df = transformer2.apply_joins("emp_payroll")
# df = transformer.apply_transformations("employee", df)
#df = transformer.apply_transformations("employee_expr_new", df_employee)
#df = df.select(tgt_cols)
#writer = TableWriter("scratch/mike/h2r_silver_head_count_poc.yml")
#writer.write_table("silver_head_count_poc", df)

INFO:adm.integration.base_integration:Starting transformations for ID: req_report

In [0]:
#Source/adm_integration_framework/scratch/mike/h2r_head_count_poc.yml
#table_reader = TableReader("scratch/mike/h2r_silver_head_count_poc.yml")
#df_payroll = table_reader.read_source_table("payroll")
#df_employee= table_reader.read_source_table("employee")
#display(df_employee.select("bus_id","bus_id_trim"))
#display(result_df.selectExpr("* except(Emp_ID, First_Name)"))

In [0]:
#transformer = BaseDataTransformer("scratch/mike/h2r_head_count_poc.yml")
#tx = "rn"

#result_df = transformer.apply_transformations("rn", result_df)
#result_df = transformer.apply_transformations("cast_cols", result_df)
#display(result_df)
#display(transformed_df.selectExpr("*", "cast(overtime_pay as decimal(10,2)) as overtime_pay"))
# why do i need to setup logger here?
# fixed by adding self.logger to adm_base_data_transformer

# column expressions duplicate columns if * specified

#transformer = DataTransformer("scratch/mike/h2r_silver_head_count_poc.yml")
#result_df = transformer.apply_joins("emp_payroll")

In [0]:
display(result_df)

In [0]:
df = result_df.transform(p2c_custom_tranformatin, Col, cole3)

In [0]:
writer = TableWriter("scratch/mike/h2r_silver_head_count_poc.yml")
# why does writer create the table?
# why does it need a schema file?
writer.write_table("silver_head_count_poc", result_df)

In [0]:
for x in spark.table("sandbox.h2r_dbx_poc.ec_employee").columns:
    print(x)

In [0]:
for x in spark.table("sandbox.h2r_dbx_poc.ec_payroll").columns:
    print(x)